### PR TITLE
Update example for 3D and new gfx APIs

### PR DESCRIPTION
**Pull request by ian-h-chamberlain**
Update the example for new changes in `ctru` APIs, especially https://github.com/rust3ds/ctru-rs/pull/116 and https://github.com/rust3ds/ctru-rs/pull/118

Also added 3D rendering to the example because it proves out a use case we will definitely want eventually, and it wasn't too hard to add! It still looks about the same if the 3D slider is turned all the way off.

- [x] This should probably not merge until those are finalized and merged

### CODE REVIEW

**Comment by Firepal** [comment]
citro3d provides a dedicated `Mtx_PerspStereoTilt` for creating a tilted perspective matrix, and we should use `ctru_sys::osGetSliderValue` to adjust the strength of the tilt

**Comment by ian-h-chamberlain** [comment]
@Firepal thanks, I created a new issue for those since I think it would make sense to add safe APIs for those (plus a bunch of the other "math" / matrix data types) to use in the example.

@rust3ds/active I think with the two `ctru-rs` PRs done this should be ready to go, if you don't mind taking a look.

**Comment by ian-h-chamberlain** [comment]
> citro3d provides a dedicated `Mtx_PerspStereoTilt` for creating a tilted perspective matrix, and we should use `ctru_sys::osGetSliderValue` to adjust the strength of the tilt

I added these changes to #16 (to avoid too many conflicts). Providing a safe API would still be preferable but I think at least the usage should be a bit more canonical now, I think.

**Comment by ian-h-chamberlain** [comment]
Hey @rust3ds/active I know people are probably busy but any chance I could get a review approval so I can merge this? Also @Meziu if you want to give me admin access on this repo I could probably merge it (and future PRs) myself without approval, since it seems like most everyone doesn't have much spare time to review changes on this repo. 

I'm hoping to push ahead with `citro3d-rs` development a bit, but I don't want to bog down others so I can just work on development by myself if that's easier. But I will need higher permissions to do that.

Thanks!

**Review by Meziu — APPROVED** [review]
> Hey @rust3ds/active I know people are probably busy but any chance I could get a review approval so I can merge this? Also @Meziu if you want to give me admin access on this repo I could probably merge it (and future PRs) myself without approval, since it seems like most everyone doesn't have much spare time to review changes on this repo.

Yeah, I'm pretty low on free time these days, which means I mostly use the time I have to relax from my other tasks or work on miscellaneous changes for `ctru-rs`, which I intend on making a PR for soon (I hope).

> I'm hoping to push ahead with `citro3d-rs` development a bit, but I don't want to bog down others so I can just work on development by myself if that's easier. But I will need higher permissions to do that.

That'd be great! Having someone working on this crate is a nice thing, especially since I always focus on `ctru-rs` and the general toolchain.

In the mean time I gave you admin permissions on this repository (since I trust you with your work). Only thing: please make sure to document your progress (in PRs) nicely since I usually read all these posts when they get published 😄.

**Comment by ian-h-chamberlain** [comment]
@Meziu thanks! I plan to set up some CI so that PRs will be the only way to merge changes anyway, but I'll also try and make sure I write up useful descriptions as well. Hopefully I won't do anything too controversial with these new powers :stuck_out_tongue_winking_eye:

**Pull request merged**
